import { useCallback, useState } from 'react'
import { Pressable, ScrollView, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { useFocusEffect } from 'expo-router'
import { Ionicons } from '@expo/vector-icons'
import * as Print from 'expo-print'
import * as Sharing from 'expo-sharing'
import { DogPicker } from '../src/DogPicker'
import { dogService,type MobileDog,type WeightRecord } from '../src/database'
import { colors,common } from '../src/theme'

export default function Reports(){const [dogs,setDogs]=useState<MobileDog[]>([]),[dogId,setDogId]=useState<string|null>(null),[weights,setWeights]=useState<WeightRecord[]>([]);useFocusEffect(useCallback(()=>{void dogService.list().then(setDogs)},[]));const dog=dogs.find(d=>d.id===dogId);async function choose(id:string|null){setDogId(id);setWeights(id?await dogService.weights(id):[])}async function pdf(){if(!dog)return;const rows=weights.map(w=>`<tr><td>${new Date(`${w.date}T12:00`).toLocaleDateString('pt-BR')}</td><td>${(w.weightGrams/1000).toLocaleString('pt-BR')} kg</td><td>${w.bodyConditionScore??'—'}/9</td></tr>`).join('');const file=await Print.printToFileAsync({html:`<html><body style="font-family:Arial;padding:30px"><h1>Ficha de ${dog.name}</h1><p><b>Registro:</b> ${dog.registeredName||'—'}</p><p><b>Nascimento:</b> ${new Date(`${dog.birthDate}T12:00`).toLocaleDateString('pt-BR')}</p><p><b>Raça:</b> ${dog.breed}</p><p><b>Sexo:</b> ${dog.sex==='female'?'Fêmea':'Macho'}</p><p><b>Cor:</b> ${dog.color||'—'}</p><h2>Pesagens</h2><table border="1" cellpadding="8" cellspacing="0"><tr><th>Data</th><th>Peso</th><th>BCS</th></tr>${rows}</table><p>${dog.notes||''}</p></body></html>`});await Sharing.shareAsync(file.uri,{mimeType:'application/pdf',dialogTitle:`Ficha de ${dog.name}`})}return <SafeAreaView style={common.screen} edges={['top','left','right']}><ScrollView contentContainerStyle={common.content}><Text style={common.eyebrow}>DOCUMENTOS</Text><Text style={common.title}>Relatórios</Text><Text style={common.subtitle}>Visualize a ficha completa antes de compartilhar o PDF.</Text><Text style={common.label}>SELECIONE O CÃO</Text><DogPicker dogs={dogs} value={dogId} onChange={id=>void choose(id)}/>{dog&&<View style={common.card}><Text style={{color:colors.text,fontSize:23,fontWeight:'900'}}>{dog.name}</Text><Text style={[common.muted,{marginBottom:14}]}>{dog.registeredName||'Sem nome de registro'}</Text>{[['Nascimento',new Date(`${dog.birthDate}T12:00`).toLocaleDateString('pt-BR')],['Raça',dog.breed],['Cor',dog.color||'—'],['Peso atual',`${dog.weightKg.toLocaleString('pt-BR')} kg`],['Pesagens',String(weights.length)]].map(([l,v])=><View key={l} style={{flexDirection:'row',justifyContent:'space-between',paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line}}><Text style={common.muted}>{l}</Text><Text style={{color:colors.text,fontWeight:'800'}}>{v}</Text></View>)}<Pressable style={[common.button,{marginTop:18}]} onPress={()=>void pdf()}><Ionicons name="document-outline" size={19} color="white"/><Text style={common.buttonText}>Compartilhar ficha em PDF</Text></Pressable></View>}</ScrollView></SafeAreaView>}
