import { useMemo, useState } from 'react'
import { Modal, Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Ionicons } from '@expo/vector-icons'
import type { MobileDog } from './database'
import { colors, common } from './theme'

export function DogPicker({dogs,value,onChange,optional=false}:{dogs:MobileDog[];value:string|null;onChange:(id:string|null)=>void;optional?:boolean}){
  const [open,setOpen]=useState(false),[query,setQuery]=useState('')
  const selected=dogs.find(d=>d.id===value),visible=useMemo(()=>dogs.filter(d=>`${d.name} ${d.registeredName} ${d.breed}`.toLowerCase().includes(query.toLowerCase())),[dogs,query])
  return <><Pressable style={[common.input,{marginBottom:14,flexDirection:'row',alignItems:'center',gap:10}]} onPress={()=>setOpen(true)}><Ionicons name="search" size={18} color={colors.blue}/><Text style={{color:selected?colors.text:colors.muted,flex:1}}>{selected?`${selected.name} • ${selected.breed}`:'Toque para selecionar o cão'}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={common.modalBackdrop}><SafeAreaView style={common.sheet} edges={['bottom']}><View style={{flexDirection:'row',alignItems:'center',marginBottom:14}}><View style={{flex:1}}><Text style={common.eyebrow}>PLANTEL</Text><Text style={[common.title,{fontSize:24}]}>Selecionar cão</Text></View><Pressable style={common.iconButton} onPress={()=>setOpen(false)}><Ionicons name="close" size={22} color={colors.text}/></Pressable></View><View style={[common.input,{flexDirection:'row',alignItems:'center',gap:8}]}><Ionicons name="search" size={18} color={colors.muted}/><TextInput autoFocus style={{color:colors.text,flex:1}} value={query} onChangeText={setQuery} placeholder="Buscar por nome ou raça" placeholderTextColor={colors.muted}/></View><ScrollView keyboardShouldPersistTaps="handled">{optional&&<Pressable style={common.card} onPress={()=>{onChange(null);setOpen(false)}}><Text style={{color:colors.text,fontWeight:'800'}}>Sem cão vinculado</Text></Pressable>}{visible.map(d=><Pressable key={d.id} style={[common.card,d.id===value&&common.selected]} onPress={()=>{onChange(d.id);setOpen(false)}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><Ionicons name="paw" size={22} color={colors.blue}/><View style={{flex:1}}><Text style={{color:colors.text,fontWeight:'900',fontSize:17}}>{d.name}</Text><Text style={common.muted}>{d.breed} • {d.weightKg.toLocaleString('pt-BR')} kg</Text></View><Ionicons name="checkmark-circle" size={20} color={d.id===value?colors.green:colors.muted}/></View></Pressable>)}{!visible.length&&<Text style={[common.muted,{textAlign:'center',padding:25}]}>Nenhum animal encontrado.</Text>}</ScrollView></SafeAreaView></View></Modal></>
}
