export type VetTopic = {
  id: string;
  category: string;
  title: string;
  summary: string;
  details: string;
  source: string;
  sourceName: string;
  keywords: string[];
};
const WSAVA =
  "https://wsava.org/Global-Guidelines/Global-Nutrition-Guidelines/";
const LIFE =
  "https://www.aaha.org/resources/life-stage-canine-2019/life-stage-canine-2019-2/";
const CHECK =
  "https://www.aaha.org/resources/life-stage-canine-2019/life-stage-checklist/";
const WEIGHT =
  "https://www.aaha.org/resources/2021-aaha-nutrition-and-weight-management-guidelines/prevention-of-obesity/";
const VACCINE =
  "https://www.aaha.org/resources/2022-aaha-canine-vaccination-guidelines/recommendations-for-core-and-noncore-canine-vaccines/";
const DENTAL = "https://www.aaha.org/resources/your-pets-dental-care/";
const EMERGENCY =
  "https://www.merckvetmanual.com/special-pet-topics/emergencies/evaluation-and-initial-treatment-of-dog-and-cat-emergencies";
const REPRO =
  "https://www.merckvetmanual.com/dog-owners/reproductive-disorders-of-dogs/management-of-reproduction-in-dogs";
const PARASITES =
  "https://www.aaha.org/wp-content/uploads/globalassets/02-guidelines/canine-life-stage-2019/2019-aaha-canine-life-stage-guidelines-final.pdf";
const FDA =
  "https://www.fda.gov/animal-veterinary/animal-health-literacy/questions-answers-fdas-work-potential-causes-non-hereditary-dcm-dogs";
const topic = (
  category: string,
  title: string,
  summary: string,
  details: string,
  source = LIFE,
  sourceName = "AAHA",
  keywords: string[] = [],
): VetTopic => ({
  id: title
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-"),
  category,
  title,
  summary,
  details,
  source,
  sourceName,
  keywords,
});
export const veterinaryTopics: VetTopic[] = [
  topic(
    "Peso e nutrição",
    "O que é BCS?",
    "BCS estima a gordura corporal pela observação e palpação.",
    "Na escala de 9 pontos, 4–5 geralmente representa condição ideal. Costelas devem ser palpáveis sem excesso de gordura, cintura visível de cima e retração abdominal de lado. O número não substitui avaliação veterinária.",
    WSAVA,
    "WSAVA",
    ["escore", "corporal", "gordura"],
  ),
  topic(
    "Peso e nutrição",
    "Como avaliar BCS 1–3/9",
    "Faixa de condição corporal abaixo do ideal.",
    "Costelas e proeminências ósseas ficam progressivamente mais evidentes e há pouca cobertura de gordura. Perda muscular deve ser avaliada separadamente. Procure o veterinário se houver emagrecimento não planejado.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "Como avaliar BCS 4–5/9",
    "Faixa geralmente considerada ideal.",
    "Costelas são facilmente palpáveis, há cintura vista de cima e retração abdominal lateral. Raça, pelagem e conformação exigem palpação, não apenas fotografia.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "Como avaliar BCS 6–9/9",
    "Faixa de excesso de gordura até obesidade.",
    "Costelas tornam-se difíceis de palpar, cintura diminui ou desaparece e depósitos de gordura aumentam. Mudanças de dieta devem ser planejadas com o veterinário.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "BCS não é peso na balança",
    "Dois cães com o mesmo peso podem ter condições corporais diferentes.",
    "O peso mede massa total; o BCS estima gordura. Use os dois ao longo do tempo e acrescente avaliação muscular.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "O que é MCS?",
    "MCS avalia a massa muscular, não a gordura.",
    "Observe e palpe coluna, escápulas, crânio e pelve. Um cão pode estar acima do peso e ainda perder músculo, especialmente quando idoso ou doente.",
    WSAVA,
    "WSAVA",
    ["musculo", "massa muscular"],
  ),
  topic(
    "Peso e nutrição",
    "Existe peso ideal por idade?",
    "Não existe uma tabela universal segura para todas as raças.",
    "O alvo deve considerar raça, sexo, porte esperado, crescimento, BCS e MCS. Curvas de crescimento e avaliação veterinária são mais úteis que um único número por idade.",
    CHECK,
    "AAHA",
    ["filhote", "crescimento"],
  ),
  topic(
    "Peso e nutrição",
    "Acompanhar crescimento do filhote",
    "O padrão ao longo do tempo importa mais que uma pesagem isolada.",
    "Registre peso regularmente, observe BCS e compare a trajetória com o porte adulto previsto. Crescimento excessivamente rápido em raças grandes aumenta preocupação ortopédica.",
    CHECK,
    "AAHA",
  ),
  topic(
    "Peso e nutrição",
    "Porção é calculada por calorias",
    "Gramas dependem da densidade energética da ração.",
    "Use kcal/kg ou kcal por porção informadas pelo fabricante. A mesma quantidade em gramas pode fornecer calorias muito diferentes entre produtos.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "RER e necessidade diária",
    "RER é uma estimativa de energia em repouso.",
    "Fatores de fase de vida e atividade transformam o RER em estimativa diária. É ponto de partida: peso, BCS e evolução real determinam ajustes.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "Petiscos até 10%",
    "Petiscos podem desequilibrar a dieta e somar muitas calorias.",
    "A AAHA recomenda manter petiscos e extras em até 10% das calorias diárias, contabilizando restos, suplementos mastigáveis e alimentos usados para medicamentos.",
    WEIGHT,
    "AAHA",
  ),
  topic(
    "Peso e nutrição",
    "Pesar ração é mais preciso",
    "Copos medidores variam bastante em pequenas porções.",
    "Uma balança de cozinha em gramas melhora a consistência. Registre tudo que o animal recebe, inclusive petiscos.",
    WEIGHT,
    "AAHA",
  ),
  topic(
    "Peso e nutrição",
    "Mudança de ração gradual",
    "Transições bruscas podem causar desconforto gastrointestinal.",
    "Faça a transição progressivamente conforme orientação do fabricante ou veterinário e monitore fezes, apetite, vômito e coceira.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Peso e nutrição",
    "Dietas grain-free e DCM",
    "Não há explicação simples ou causalidade definitiva.",
    "A FDA encontrou relatos associados a dietas com alta presença de leguminosas, mas vários fatores podem participar. Não mude tratamento com base em rumor; converse com veterinário ou nutricionista veterinário.",
    FDA,
    "FDA",
  ),
  topic(
    "Peso e nutrição",
    "Água sempre disponível",
    "Hidratação é parte essencial da nutrição.",
    "Mantenha água fresca e limpa acessível. Aumento ou redução persistente do consumo pode justificar avaliação clínica.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Filhotes",
    "Fases da vida variam com o porte",
    "Raça e tamanho mudam a velocidade de maturação.",
    "A AAHA define filhote até o fim do crescimento rápido, aproximadamente 6–9 meses, com variação. Maturação física completa pode levar mais tempo em cães grandes.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Filhotes",
    "Frequência das refeições",
    "Filhotes normalmente precisam refeições menores e mais frequentes.",
    "A frequência depende de idade, porte e saúde. Distribua a quantidade diária e mantenha horários regulares; raças toy podem exigir atenção especial.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Filhotes",
    "Socialização segura",
    "Experiências precoces devem ser positivas e proporcionais ao risco sanitário.",
    "Converse com o veterinário sobre socialização, vacinação e exposição. Evite tanto isolamento completo quanto ambientes de alto risco não controlados.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Filhotes",
    "Dentes de leite persistentes",
    "Dentes decíduos retidos podem alterar o encaixe e acumular placa.",
    "Peça avaliação durante o desenvolvimento da dentição, especialmente se dois dentes ocuparem a mesma posição.",
    CHECK,
    "AAHA",
  ),
  topic(
    "Filhotes",
    "Raças grandes e crescimento",
    "Crescimento controlado e BCS ideal ajudam a reduzir risco ortopédico.",
    "Use alimento completo formulado para crescimento de porte grande quando indicado e não adicione cálcio sem orientação veterinária.",
    CHECK,
    "AAHA",
  ),
  topic(
    "Vacinação",
    "Vacinas essenciais",
    "Protegem contra doenças graves e algumas zoonoses.",
    "A AAHA lista cinomose, adenovírus, parvovírus, leptospirose e raiva como essenciais, considerando contraindicações médicas e regras locais.",
    VACCINE,
    "AAHA",
  ),
  topic(
    "Vacinação",
    "Série inicial do filhote",
    "Anticorpos maternos podem interferir na resposta inicial.",
    "Para combinações virais essenciais, a AAHA orienta doses entre 6 e 16 semanas, em intervalos de 2–4 semanas. O veterinário define o protocolo do produto.",
    VACCINE,
    "AAHA",
  ),
  topic(
    "Vacinação",
    "Reforço após série inicial",
    "A proteção precisa ser consolidada.",
    "A combinação de cinomose, adenovírus e parvovírus recebe uma dose dentro de um ano após a série inicial; reforços posteriores seguem diretriz e rótulo.",
    VACCINE,
    "AAHA",
  ),
  topic(
    "Vacinação",
    "Vacina contra raiva",
    "É essencial e também questão de saúde pública.",
    "Idade, intervalo e obrigação legal variam por local. Siga a legislação e o veterinário responsável.",
    VACCINE,
    "AAHA",
  ),
  topic(
    "Vacinação",
    "Vacinas conforme estilo de vida",
    "Bordetella, influenza e outras dependem da exposição.",
    "Hotel, creche, exposições, viagens, contato com água parada, fauna e região geográfica mudam o risco. Reavalie anualmente.",
    VACCINE,
    "AAHA",
  ),
  topic(
    "Vacinação",
    "Reação após vacina",
    "Eventos adversos devem ser registrados e comunicados.",
    "Procure atendimento urgente diante de dificuldade respiratória, colapso, inchaço facial intenso ou sinais graves. Informe produto, lote e horário da aplicação.",
    VACCINE,
    "AAHA",
  ),
  topic(
    "Parasitas",
    "Controle durante todo o ano",
    "Pulgas, carrapatos e parasitas internos não são apenas problemas sazonais.",
    "O plano deve considerar região, viagens, estilo de vida e produto usado. Nunca combine produtos sem confirmar segurança.",
    PARASITES,
    "AAHA/CAPC",
  ),
  topic(
    "Parasitas",
    "Prevenção de dirofilariose",
    "A doença do verme do coração é prevenível.",
    "A AAHA/CAPC recomenda prevenção contínua e testes segundo idade e risco regional. A escolha do medicamento é veterinária.",
    PARASITES,
    "AAHA/CAPC",
  ),
  topic(
    "Parasitas",
    "Exame de fezes",
    "Animais sem sintomas também podem eliminar parasitas.",
    "A frequência do exame varia com idade, estilo de vida e prevenção; diretrizes citam avaliações periódicas individualizadas.",
    PARASITES,
    "AAHA/CAPC",
  ),
  topic(
    "Parasitas",
    "Carrapatos transmitem doenças",
    "A picada pode transmitir agentes infecciosos.",
    "Inspecione pele após exposição e use prevenção adequada. Fraqueza, febre, palidez ou sangramentos exigem avaliação.",
    PARASITES,
    "AAHA/CAPC",
  ),
  topic(
    "Saúde bucal",
    "Escovação diária",
    "É a melhor medida doméstica para reduzir acúmulo de placa.",
    "Use escova e produto apropriado para cães; pasta humana não é indicada. Introduza o cuidado gradualmente e com reforço positivo.",
    DENTAL,
    "AAHA",
  ),
  topic(
    "Saúde bucal",
    "Mau hálito não é normal",
    "Pode ser o primeiro sinal de doença dental.",
    "Tártaro, gengiva vermelha, sangramento, dor, salivação ou dificuldade para comer justificam exame veterinário.",
    DENTAL,
    "AAHA",
  ),
  topic(
    "Saúde bucal",
    "Limpeza sem anestesia é insuficiente",
    "Remove principalmente o que está visível.",
    "Sem anestesia não é possível examinar e limpar adequadamente sob a gengiva, fazer radiografias completas e proteger a via aérea.",
    DENTAL,
    "AAHA",
  ),
  topic(
    "Saúde bucal",
    "Radiografia dental",
    "Muita doença fica escondida abaixo da gengiva.",
    "Radiografias intraorais ajudam a avaliar raízes, osso e dentes aparentemente ausentes. São parte da avaliação completa quando indicada.",
    DENTAL,
    "AAHA",
  ),
  topic(
    "Prevenção",
    "Consulta preventiva individualizada",
    "A prevenção muda com idade, raça e estilo de vida.",
    "Uma consulta inclui exame físico e revisão de nutrição, comportamento, dentes, vacinas, parasitas e riscos ambientais.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Prevenção",
    "Microchip e identificação",
    "Identificação permanente aumenta a chance de retorno.",
    "Mantenha cadastro e telefone atualizados e use também plaqueta legível. Confirme periodicamente se o chip é detectado.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Prevenção",
    "Exames no cão sênior",
    "Doenças podem começar antes de sinais claros.",
    "A frequência e o painel dependem do indivíduo. Hemograma, bioquímica, urina, pressão e testes regionais podem ser recomendados pelo veterinário.",
    CHECK,
    "AAHA",
  ),
  topic(
    "Prevenção",
    "Mudança de comportamento é dado clínico",
    "Dor e doença podem parecer “teimosia” ou envelhecimento.",
    "Registre alterações de sono, interação, apetite, eliminação, mobilidade e tolerância ao toque.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Reprodução",
    "Intervalo entre cios varia",
    "Não existe calendário idêntico para todas as fêmeas.",
    "O intervalo pode variar aproximadamente de 4 a 13 meses; porte, raça e indivíduo influenciam. Registre início, duração e sinais.",
    REPRO,
    "Merck Veterinary Manual",
  ),
  topic(
    "Reprodução",
    "Proestro e estro",
    "As fases não devem ser definidas apenas pelo sangramento.",
    "No proestro a fêmea atrai machos mas geralmente não aceita monta; no estro torna-se receptiva. Citologia e hormônios melhoram a precisão.",
    REPRO,
    "Merck Veterinary Manual",
  ),
  topic(
    "Reprodução",
    "Momento fértil exige avaliação",
    "Contar dias desde o início do cio é impreciso.",
    "Dosagem de progesterona e citologia vaginal, interpretadas pelo veterinário, ajudam a estimar ovulação e momento de cobertura.",
    REPRO,
    "Merck Veterinary Manual",
  ),
  topic(
    "Reprodução",
    "Duração da gestação",
    "A referência depende de como a data foi determinada.",
    "A gestação é frequentemente descrita em torno de 62–64 dias, mas contar somente desde a cobertura gera variação. Acompanhe com veterinário.",
    REPRO,
    "Merck Veterinary Manual",
  ),
  topic(
    "Reprodução",
    "Dificuldade no parto é emergência",
    "Contrações improdutivas ou sofrimento exigem contato imediato.",
    "Não administre ocitocina, cálcio ou outros medicamentos sem avaliação. Distocia pode colocar mãe e filhotes em risco.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Reprodução",
    "Exames antes do acasalamento",
    "Saúde reprodutiva inclui mais que fertilidade.",
    "Avalie doenças hereditárias da raça, brucelose, condição corporal, vacinação e saúde geral de ambos os cães com profissionais habilitados.",
    CHECK,
    "AAHA",
  ),
  topic(
    "Emergências",
    "Dificuldade para respirar",
    "Respiração trabalhosa ou coloração azulada é emergência.",
    "Mantenha o animal calmo, reduza manipulação e procure atendimento imediatamente. Não force comida ou água.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Emergências",
    "Convulsão prolongada ou repetida",
    "Crises contínuas ou em sequência precisam de atendimento urgente.",
    "Afaste objetos, cronometre, filme se for seguro e não coloque a mão na boca. Siga o plano prescrito se já existir.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Emergências",
    "Suspeita de intoxicação",
    "Não provoque vômito sem orientação.",
    "Guarde embalagem, quantidade provável e horário. Contate imediatamente veterinário ou centro de toxicologia; algumas substâncias pioram ao vomitar.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Emergências",
    "Dilatação abdominal e tentativas de vomitar",
    "Pode indicar dilatação-torção gástrica.",
    "Barriga aumentando, inquietação, salivação e tentativas improdutivas de vômito exigem emergência imediata, sobretudo em cães de peito profundo.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Emergências",
    "Golpe de calor",
    "Temperatura ambiental elevada pode causar falência de órgãos.",
    "Leve para ambiente fresco, inicie resfriamento moderado com água fresca e ventilação e vá ao atendimento. Evite gelo ou resfriamento extremo.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Emergências",
    "Sangramento intenso",
    "Pressão direta é a primeira medida enquanto busca ajuda.",
    "Use pano limpo e pressão firme contínua. Não fique removendo o curativo para conferir e procure emergência.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Emergências",
    "Trauma mesmo sem ferida visível",
    "Atropelamento e quedas podem causar lesões internas.",
    "Restrinja movimento, transporte com apoio e procure avaliação. Respiração, consciência e circulação têm prioridade.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Sinais clínicos",
    "Vômitos repetidos",
    "Frequência e estado geral determinam urgência.",
    "Vômitos repetidos, sangue, dor, distensão, fraqueza, filhote ou incapacidade de manter água exigem avaliação rápida.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Sinais clínicos",
    "Diarreia com sangue ou prostração",
    "Desidratação pode evoluir rapidamente.",
    "Filhotes, idosos e cães pequenos têm menor reserva. Sangue, vômitos associados ou prostração justificam atendimento.",
    EMERGENCY,
    "Merck Veterinary Manual",
  ),
  topic(
    "Sinais clínicos",
    "Apetite reduzido",
    "Uma mudança persistente pode ser sinal precoce de doença.",
    "Registre duração, ingestão de água, vômitos, fezes, medicamentos e mudanças na dieta. Filhotes e diabéticos merecem urgência maior.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Sinais clínicos",
    "Sede ou urina aumentada",
    "Pode ocorrer em doenças endócrinas, renais e outras condições.",
    "Não restrinja água. Meça aproximadamente o consumo e procure o veterinário se a alteração persistir.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Sinais clínicos",
    "Dor pode ser discreta",
    "Cães frequentemente alteram postura e rotina antes de vocalizar.",
    "Observe dificuldade ao levantar, recusa de escadas, ofegação em repouso, isolamento, irritabilidade ou lambedura localizada.",
    LIFE,
    "AAHA",
  ),
  topic(
    "Sênior",
    "Perda muscular no envelhecimento",
    "Peso estável não garante músculo preservado.",
    "Avalie MCS, mobilidade e ingestão proteica com o veterinário. Doença, dor e redução de atividade podem acelerar perda muscular.",
    WSAVA,
    "WSAVA",
  ),
  topic(
    "Sênior",
    "Adaptação da casa",
    "Mudanças ambientais podem reduzir dor e quedas.",
    "Pisos antiderrapantes, rampas, cama adequada e acesso fácil a água ajudam cães com mobilidade reduzida.",
    CHECK,
    "AAHA",
  ),
  topic(
    "Sênior",
    "Envelhecimento não explica tudo",
    "Alterações novas precisam ser investigadas.",
    "Confusão, acidentes urinários, emagrecimento, tosse, intolerância ao exercício ou dor não devem ser automaticamente atribuídos à idade.",
    CHECK,
    "AAHA",
  ),
];
